#!/bin/bash
#
# AI Consultant Toolkit - Phase 2: Configuration & MCP Setup (macOS)
# Configures EA persona and sets up MCP servers (assumes skills already installed via Claude Code)
# No admin rights required
#

set -e
SKIP_MCPS=false

# Parse arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --skip-mcps) SKIP_MCPS=true ;;
        *) echo "Unknown parameter: $1"; exit 1 ;;
    esac
    shift
done

START_TIME=$(date +%s)
RESULTS_FILE="$HOME/setup-phase2-results.json"
INSTRUCTIONS_FILE="$HOME/mcp-setup-instructions.txt"

# Colors
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${CYAN}================================================================${NC}"
echo -e "${CYAN}   AI Consultant Toolkit - Phase 2 Setup${NC}"
echo -e "${CYAN}   Configuration & MCP Server Setup${NC}"
echo -e "${CYAN}================================================================${NC}"

# Verify Claude Code installed
echo -e "\n${YELLOW}> Verifying Claude Code installation...${NC}"
if ! command -v claude &> /dev/null; then
    echo -e "${RED}  [FAIL] Claude Code not found. Please complete Phase 1 first.${NC}"
    exit 1
fi
echo -e "${GREEN}  [OK] Claude Code detected${NC}"

# Check installed skills
echo -e "\n${YELLOW}> Checking installed skills...${NC}"
SETTINGS_FILE="$HOME/.claude/settings.json"
SKILLS_FOUND=()

if [ -f "$SETTINGS_FILE" ]; then
    # Check for key skills
    for skill in superpowers document-skills episodic-memory playwright executive-assistant; do
        if grep -q "$skill" "$SETTINGS_FILE" 2>/dev/null; then
            SKILLS_FOUND+=("$skill")
        elif [ -d "$HOME/.claude/skills/$skill" ]; then
            SKILLS_FOUND+=("$skill")
        fi
    done

    echo -e "${GREEN}  [OK] Found ${#SKILLS_FOUND[@]} skills installed${NC}"
    for skill in "${SKILLS_FOUND[@]}"; do
        echo -e "${CYAN}  [INFO]   - $skill${NC}"
    done
else
    echo -e "${YELLOW}  [WARN] Settings file not found - skills may not be configured yet${NC}"
fi

# Create MCP directories
echo -e "\n${YELLOW}> Creating MCP directories...${NC}"
mkdir -p "$HOME/mcp-servers"
echo -e "${GREEN}  [OK] MCP directory ready${NC}"

# Configure EA as default persona
echo -e "\n${CYAN}================================================================${NC}"
echo -e "${CYAN}   Configuring Executive Assistant${NC}"
echo -e "${CYAN}================================================================${NC}"

echo -e "\n${YELLOW}> Creating CLAUDE.md with EA default persona...${NC}"
CLAUDE_MD="$HOME/CLAUDE.md"

# Backup existing CLAUDE.md if it exists
if [ -f "$CLAUDE_MD" ]; then
    BACKUP_FILE="$CLAUDE_MD.backup.$(date +%Y%m%d%H%M%S)"
    cp "$CLAUDE_MD" "$BACKUP_FILE"
    echo -e "${CYAN}  [INFO] CLAUDE.md already exists - creating backup${NC}"
    echo -e "${CYAN}  [INFO] Backup saved at $BACKUP_FILE${NC}"
fi

# Create new CLAUDE.md
cat > "$CLAUDE_MD" <<'EOF'
# Claude Code Configuration

## Default Persona
- Always operate as Executive Assistant (EA/Evie) unless user explicitly asks for "regular Claude"
- Use warm, British female voice and personality
- Proactive, caring, organized, with gentle warmth
- Track context across sessions using episodic memory
- Can switch to neutral technical mode for deep coding/debugging

## Communication Style
- Address user directly by name when known
- Morning briefings at start of day
- Proactive reminders for important tasks
- Email triage and calendar management
- Celebrate wins, gentle with feedback

## Available Skills
- /executive-assistant - Full EA persona and workflows
- /superpowers - Systematic debugging, planning, code review
- /document-skills - Create/edit DOCX, PDF, PPTX, XLSX files
- /playwright-skill - Browser automation and testing
- /episodic-memory - Search across previous conversations

## MCP Integrations
- Gmail - Email management with attachment support
- Google Calendar - Schedule management
- Google Drive - File storage and sharing
- GitHub - Version control and collaboration
- Stripe - Payment processing (when configured)

## How to Switch Modes
- "Exit EA mode" or "Be regular Claude for this task" - Temporarily switch to neutral mode
- "Resume EA mode" - Return to Executive Assistant persona
- Deep technical work automatically uses neutral technical mode

---
Generated by AI Consultant Toolkit - Phase 2
Generated: $(date '+%Y-%m-%d %H:%M:%S')
EOF

echo -e "${GREEN}  [OK] CLAUDE.md created at $CLAUDE_MD${NC}"
echo -e "${CYAN}  [INFO] EA configured as default persona${NC}"

# MCP Server Setup Instructions
if [ "$SKIP_MCPS" = false ]; then
    echo -e "\n${CYAN}================================================================${NC}"
    echo -e "${CYAN}   MCP Server Setup${NC}"
    echo -e "${CYAN}================================================================${NC}"

    echo -e "${CYAN}  [INFO] MCP servers require manual OAuth setup${NC}"
    echo -e "${CYAN}  [INFO] The following instructions will guide you through authentication${NC}"

    # Create setup instructions file
    cat > "$INSTRUCTIONS_FILE" <<EOF
AI Consultant Toolkit - Phase 2 MCP Setup Instructions
========================================================
Generated: $(date '+%Y-%m-%d %H:%M:%S')

IMPORTANT: MCP servers are already available in Claude Code.
You just need to authenticate them to use with your accounts.

Prerequisites:
1. Claude Code must be authenticated: claude auth
2. GitHub CLI must be authenticated: gh auth login

---

STEP 1: Authenticate GitHub (if not already done)
===================================================
Run in Terminal:
  gh auth login

Follow prompts:
  - Choose: GitHub.com
  - Protocol: HTTPS
  - Authenticate: Login with web browser
  - Complete browser authentication

Verify:
  gh auth status

Result: GitHub MCP will automatically work via gh CLI authentication

---

STEP 2: Google Services Authentication
========================================
Google services (Gmail, Calendar, Drive) require OAuth tokens.

NOTE: These are custom MCP servers that need to be installed separately.
They are not included in Claude Code by default.

To set up Google MCP servers:
1. Visit: https://github.com/PerryB-GIT/claude-code-config
2. Navigate to: mcp-servers/gmail/, google-calendar/, google-drive/
3. Clone the repositories to: ~/mcp-servers/
4. Run npm install in each directory
5. Run OAuth authentication for each service

Example for Gmail:
  cd ~/mcp-servers/gmail
  npm install
  npm run auth

This will:
  - Open browser for Google OAuth
  - Grant access to Gmail API
  - Save token to ~/.gmail-mcp/tokens.json

Repeat for Calendar and Drive:
  cd ~/mcp-servers/google-calendar
  npm install
  npm run auth

  cd ~/mcp-servers/google-drive
  npm install
  npm run auth

---

STEP 3: Configure MCP Servers in Claude Code
==============================================
Add to ~/.claude/settings.json under "mcpServers":

{
  "mcpServers": {
    "gmail": {
      "command": "node",
      "args": ["/Users/YourName/mcp-servers/gmail/index.js"]
    },
    "google-calendar": {
      "command": "node",
      "args": ["/Users/YourName/mcp-servers/google-calendar/index.js"]
    },
    "google-drive": {
      "command": "node",
      "args": ["/Users/YourName/mcp-servers/google-drive/index.js"]
    }
  }
}

---

STEP 4: Restart Claude Code
============================
After configuring MCP servers, restart Claude Code:
  - Close all Claude Code sessions
  - Start fresh: claude chat

---

STEP 5: Test Your Setup
========================
Test EA with these commands:

  "Good morning"
  - Should provide briefing with email, calendar, tasks

  "Check my email"
  - Should list recent emails (requires Gmail MCP)

  "What's on my calendar today?"
  - Should show today's events (requires Calendar MCP)

  "List my Drive files"
  - Should show recent files (requires Drive MCP)

---

TROUBLESHOOTING
===============

Issue: "Gmail MCP not authenticated"
Fix: cd ~/mcp-servers/gmail && npm run auth

Issue: "Command 'node' not found"
Fix: Ensure Node.js is in PATH (restart Terminal)

Issue: "OAuth token expired"
Fix: Re-run npm run auth in the MCP directory

Issue: "MCP server not responding"
Fix: Check ~/.claude/settings.json for correct paths
      Restart Claude Code

---

NEXT STEPS
==========
1. Follow the authentication steps above
2. Test each MCP service individually
3. Once working, explore the comprehensive guides:
   - EA Configuration Guide
   - Custom Skills Walkthrough

Guide Links:
  https://github.com/PerryB-GIT/ai-consultant-toolkit/blob/main/guides/EA-CONFIGURATION-GUIDE.md
  https://github.com/PerryB-GIT/ai-consultant-toolkit/blob/main/guides/CUSTOM-SKILLS-WALKTHROUGH.md

---
EOF

    echo -e "${GREEN}  [OK] Setup instructions saved to: $INSTRUCTIONS_FILE${NC}"
    echo -e "${CYAN}  [INFO] Please review the instructions file for MCP authentication steps${NC}"
fi

# Generate results JSON
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

# Build skills array for JSON
SKILLS_JSON="["
for i in "${!SKILLS_FOUND[@]}"; do
    if [ $i -gt 0 ]; then
        SKILLS_JSON+=","
    fi
    SKILLS_JSON+="\"${SKILLS_FOUND[$i]}\""
done
SKILLS_JSON+="]"

# Create results JSON
cat > "$RESULTS_FILE" <<EOF
{
  "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "phase": "Phase 2: Configuration & MCP Setup",
  "verification": {
    "skills_installed": {
      "status": "OK",
      "verified": true,
      "skills": $SKILLS_JSON
    }
  },
  "configuration": {
    "ea_default_persona": {
      "status": "OK",
      "configured": true
    },
    "claude_md_created": {
      "status": "OK",
      "configured": true
    }
  },
  "mcps": {
    "gmail": {
      "status": "MANUAL_SETUP_REQUIRED",
      "configured": false
    },
    "google_calendar": {
      "status": "MANUAL_SETUP_REQUIRED",
      "configured": false
    },
    "google_drive": {
      "status": "MANUAL_SETUP_REQUIRED",
      "configured": false
    },
    "github": {
      "status": "MANUAL_SETUP_REQUIRED",
      "configured": false
    }
  },
  "errors": [],
  "duration_seconds": $DURATION
}
EOF

echo -e "\n${CYAN}================================================================${NC}"
echo -e "${GREEN}   Phase 2 Configuration Complete!${NC}"
echo -e "${CYAN}================================================================${NC}"
echo -e "${CYAN}Results: $RESULTS_FILE${NC}"
echo -e "${CYAN}Duration: ${DURATION}s${NC}"

echo -e "\n${YELLOW}What was configured:${NC}"
echo -e "  [OK] CLAUDE.md created with EA default persona"
echo -e "  [OK] Verified existing skills installation"
echo -e "  [OK] Created MCP setup instructions"

echo -e "\n${YELLOW}Skills found:${NC}"
if [ ${#SKILLS_FOUND[@]} -gt 0 ]; then
    for skill in "${SKILLS_FOUND[@]}"; do
        echo -e "${GREEN}  - $skill${NC}"
    done
else
    echo -e "${RED}  [WARN] No skills detected - may need manual installation${NC}"
fi

echo -e "\n${YELLOW}Next steps:${NC}"
echo "  1. Review MCP setup instructions: $INSTRUCTIONS_FILE"
echo "  2. Authenticate GitHub: gh auth login"
echo "  3. Authenticate Claude: claude auth"
echo "  4. Set up Google MCP servers (see instructions file)"
echo "  5. Restart Claude Code: exit, then claude chat"
echo "  6. Test EA: claude chat, then say Good morning"
echo "  7. Upload $RESULTS_FILE to dashboard (optional)"
